# Generated by Django 3.0.3 on 2020-08-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipForm',
            new_name='ContactForm',
        ),
    ]
